# Generated by Django 5.2.17 on 2026-09-21 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=160)),
                ('project_type', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('both', 'Interior and exterior'), ('commercial', 'Commercial space')], max_length=20)),
                ('finish_level', models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=20)),
                ('desired_start', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selections', models.JSONField(default=list)),
                ('subtotal', models.PositiveBigIntegerField()),
                ('coordination_fee', models.PositiveBigIntegerField()),
                ('location_adjustment', models.IntegerField(default=0)),
                ('estimate_low', models.PositiveBigIntegerField()),
                ('estimate_high', models.PositiveBigIntegerField()),
                ('pricing_version', models.CharField(default='2026.09', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='projects.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New inquiry'), ('contacted', 'Contacted'), ('site_visit', 'Site visit scheduled'), ('proposal', 'Proposal sent'), ('won', 'Approved'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('lost', 'Not proceeding')], default='new', max_length=20)),
                ('site_visit_at', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
